
" Note: Skip initialization for vim-tiny or vim-small.
if 0 | endif

filetype off

if has('vim_starting')
  if &compatible
    set nocompatible               " Be iMproved
  endif

  set runtimepath+=~/.vim/bundle/neobundle.vim

endif

call neobundle#begin(expand('~/.vim/bundle/'))

" originalrepos on github
NeoBundle 'Shougo/neobundle.vim'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'tpope/vim-surround'
NeoBundle 'vim-scripts/vim-auto-save'
"NeoBundle 'kannokanno/previm'
"NeoBundle 'syui/cscroll.vim'
"NeoBundle 'kana/vim-submode'
"NeoBundle 'plasticboy/vim-markdown'
""NeoBundle 'https://bitbucket.org/kovisoft/slimv'

au BufRead,BufNewFile *.md set filetype=markdown
let g:previm_open_cmd = 'open -a Firefox'

call neobundle#end()

filetype plugin indent on     " required!
filetype indent on
syntax on

NeoBundleCheck

:set noundofile
:set nobackup
:set noswapfile
